[package]
name = "fort-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrypt = "0.8"
hmac = {version = "0.11", features = ["std"]}
sha2 = "0.9" 
sha3 = "0.9"
anyhow = "1.0"
