[package]
name = "fort-rs-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
fort-rs = { path = "../" }
getrandom = {version = "0.2", features = ["js"]}
